# MkDocs Configuration
# --------------------

markdown_extensions:
    - toc:
        permalink: true
nav:
  - 'Home': index.md
  - 'API Reference':
    - 'Cards & Decks':
      - 'Card': Card.md
      - 'CardList': CardList.md
      - 'CardSet': CardSet.md
      - 'CardVariant': CardVariant.md
      - 'Deck': Deck.md
    - 'Card Catalogs & Inventory':
      - 'CardCatalog': CardCatalog.md
      - 'CardInventory': CardInventory.md
    - 'Graphical Analysis':
      - 'graphics': graphics.md
    - 'Metadata':
      - 'PlayerProfile': PlayerProfile.md
      - 'meta': meta.md
    - 'Base Classes':
        - 'CardBase': CardBase.md
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            filters: ['!^_[^_]']
            show_signature_annotations: false
            show_source: true
          paths: ['src']
  - search
repo_name: HarrisonTotty/fab
repo_url: https://github.com/HarrisonTotty/fab
site_name: Flesh and Blood TCG Analysis Library
theme:
  name: material
